export enum PHPCSMessageType {
  ERROR = 'ERROR',
  WARNING = 'WARNING',
}

/**
 * Represents a message object generated by PHPCS.
 */
export interface PHPCSMessage {
  /**
   * The message describing the issue detected by PHPCS.
   */
  message: string;

  /**
   * The source of the message, typically indicating the PHPCS standard and sniff that generated it.
   */
  source: string;

  /**
   * The severity level of the message.
   */
  severity: number;

  /**
   * Indicates whether the issue can be automatically fixed by PHPCBF.
   */
  fixable: boolean;

  /**
   * The type of the message, either ERROR or WARNING.
   */
  type: PHPCSMessageType;

  /**
   * The line number in the file where the issue was detected.
   */
  line: number;

  /**
   * The column number in the line where the issue was detected.
   */
  column: number;
}

/**
 * Counts of errors, warnings, and fixable issues in a PHPCS report.
 */
export interface PHPCSCounts {
  errors: number;
  warnings: number;
  fixable?: number;
}

/**
 * Represents the status of a file in a PHPCS report, including message
 * details and counts of errors, warnings, and fixable issues.
 */
export interface PHPCSFileStatus extends PHPCSCounts {
  /**
   * The list of message objects associated with the file.
   */
  messages: PHPCSMessage[];
}

/**
 * The PHPCS report, including totals and file-specific statuses.
 */
export interface PHPCSReport {
  /**
   * The total counts of errors, warnings, and fixable issues across all files in the report.
   */
  totals: PHPCSCounts;

  /**
   * A mapping of all files and their statuses included
   * in the PHPCS report, keyed by their file paths.
   */
  files: {
    [key: string]: PHPCSFileStatus;
  };
}
