name: Run Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Check TypeScript for errors
        run: npx tsc --noEmit

      - name: Run Linter
        run: npm run lint

      - name: Run Test
        run: xvfb-run npm test
